
; This file was generated by HiSprite.py, a sprite compiler by Quinn Dunki.
; If you feel the need to modify this file, you are probably doing it wrong.

SPACESHIP: ;6 bytes per row
	SAVE_AXY
	ldy PARAM0
	ldx MOD7_2,y
.ifpC02
	jmp (SPACESHIP_JMP,x)

SPACESHIP_JMP:
	.addr SPACESHIP_SHIFT0
	.addr SPACESHIP_SHIFT1
	.addr SPACESHIP_SHIFT2
	.addr SPACESHIP_SHIFT3
	.addr SPACESHIP_SHIFT4
	.addr SPACESHIP_SHIFT5
	.addr SPACESHIP_SHIFT6
.else
	lda SPACESHIP_JMP+1,x
	pha
	lda SPACESHIP_JMP,x
	pha
	rts

SPACESHIP_JMP:
	.addr SPACESHIP_SHIFT0-1
	.addr SPACESHIP_SHIFT1-1
	.addr SPACESHIP_SHIFT2-1
	.addr SPACESHIP_SHIFT3-1
	.addr SPACESHIP_SHIFT4-1
	.addr SPACESHIP_SHIFT5-1
	.addr SPACESHIP_SHIFT6-1
.endif


SPACESHIP_SHIFT0:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00010101
	sta (SCRATCH0),y
	iny
	lda #%00101000
	sta (SCRATCH0),y
	iny
	lda #%00000001
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010000
	sta (SCRATCH0),y
	iny
	lda #%10001010
	sta (SCRATCH0),y
	iny
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10101000
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000001
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11110101
	sta (SCRATCH0),y
	iny
	lda #%10111010
	sta (SCRATCH0),y
	iny
	lda #%10000001
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010100
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00101000
	sta (SCRATCH0),y
	iny
	lda #%01010101
	sta (SCRATCH0),y
	iny
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001010
	sta (SCRATCH0),y
	iny
	lda #%01000000
	sta (SCRATCH0),y
	iny
	lda #%00000010
	sta (SCRATCH0),y
	iny
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 481, Optimized 28 rows.



SPACESHIP_SHIFT1:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%01010100
	sta (SCRATCH0),y
	iny
	lda #%00100000
	sta (SCRATCH0),y
	iny
	lda #%00000101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10100000
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10000010
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010100
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010100
	sta (SCRATCH0),y
	iny
	lda #%11101011
	sta (SCRATCH0),y
	iny
	lda #%10000101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000001
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	sta (SCRATCH0),y
	iny
	lda #%01010101
	sta (SCRATCH0),y
	iny
	lda #%00000010
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00101000
	sta (SCRATCH0),y
	iny
	iny
	lda #%00001010
	sta (SCRATCH0),y
	iny
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 497, Optimized 26 rows.



SPACESHIP_SHIFT2:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%01010000
	sta (SCRATCH0),y
	iny
	lda #%00000010
	sta (SCRATCH0),y
	iny
	lda #%00010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000001
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10001010
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11010000
	sta (SCRATCH0),y
	iny
	lda #%10101110
	sta (SCRATCH0),y
	iny
	lda #%10010111
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010101
	sta (SCRATCH0),y
	iny
	lda #%00001010
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	sta (SCRATCH0),y
	iny
	lda #%00000001
	sta (SCRATCH0),y
	iny
	lda #%00101000
	sta (SCRATCH0),y
	iny
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 489, Optimized 27 rows.



SPACESHIP_SHIFT3:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%01000000
	sta (SCRATCH0),y
	iny
	lda #%00001010
	sta (SCRATCH0),y
	iny
	lda #%01010100
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101000
	sta (SCRATCH0),y
	iny
	lda #%10000101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11010100
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	sta (SCRATCH0),y
	iny
	lda #%10111010
	sta (SCRATCH0),y
	iny
	lda #%11011101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010100
	sta (SCRATCH0),y
	iny
	lda #%00101010
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000101
	sta (SCRATCH0),y
	iny
	lda #%00100000
	sta (SCRATCH0),y
	iny
	lda #%00000001
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 481, Optimized 28 rows.



SPACESHIP_SHIFT4:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00101010
	sta (SCRATCH0),y
	iny
	lda #%01010000
	sta (SCRATCH0),y
	iny
	lda #%00000010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10100000
	sta (SCRATCH0),y
	iny
	lda #%10010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11010000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000001
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10000010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11101010
	sta (SCRATCH0),y
	iny
	lda #%11110101
	sta (SCRATCH0),y
	iny
	lda #%10000010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101000
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010000
	sta (SCRATCH0),y
	iny
	lda #%00101010
	sta (SCRATCH0),y
	iny
	lda #%00000001
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010100
	sta (SCRATCH0),y
	iny
	iny
	lda #%00000101
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 489, Optimized 27 rows.



SPACESHIP_SHIFT5:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00101000
	sta (SCRATCH0),y
	iny
	lda #%01000001
	sta (SCRATCH0),y
	iny
	lda #%00001010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11000000
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10000101
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101000
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10001010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10101000
	sta (SCRATCH0),y
	iny
	lda #%11010111
	sta (SCRATCH0),y
	iny
	lda #%10001011
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10100000
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10000010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	sta (SCRATCH0),y
	iny
	lda #%00101010
	sta (SCRATCH0),y
	iny
	lda #%00000101
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010000
	sta (SCRATCH0),y
	iny
	iny
	lda #%00010100
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 489, Optimized 27 rows.



SPACESHIP_SHIFT6:
	ldx PARAM1
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00100000
	sta (SCRATCH0),y
	iny
	lda #%00000101
	sta (SCRATCH0),y
	iny
	lda #%00101010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	iny
	lda #%11010100
	sta (SCRATCH0),y
	iny
	lda #%10000010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	lda #%10010101
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10100000
	sta (SCRATCH0),y
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10101010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10100000
	sta (SCRATCH0),y
	iny
	lda #%11011101
	sta (SCRATCH0),y
	iny
	lda #%10101110
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	iny
	lda #%11010101
	sta (SCRATCH0),y
	iny
	lda #%10001010
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	iny
	lda #%00101010
	sta (SCRATCH0),y
	iny
	lda #%00010101
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H1,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	sta (SCRATCH0),y
	iny
	lda #%00000010
	sta (SCRATCH0),y
	iny
	lda #%01010000
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts	;Cycle count: 481, Optimized 28 rows.



