
; This file was generated by HiSprite.py, a sprite compiler by Quinn Dunki.
; If you feel the need to modify this file, you are probably doing it wrong.

BOXW_MIX: ;6 bytes per row
	SAVE_AXY
	ldy PARAM0
	ldx MOD7_2,y
	jmp (BOXW_MIX_JMP,x)

BOXW_MIX_JMP:
	.addr BOXW_MIX_SHIFT0
	.addr BOXW_MIX_SHIFT1
	.addr BOXW_MIX_SHIFT2
	.addr BOXW_MIX_SHIFT3
	.addr BOXW_MIX_SHIFT4
	.addr BOXW_MIX_SHIFT5
	.addr BOXW_MIX_SHIFT6


BOXW_MIX_SHIFT0:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	RESTORE_AXY
	rts



BOXW_MIX_SHIFT1:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11111100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11100001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11100001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11111100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	RESTORE_AXY
	rts



BOXW_MIX_SHIFT2:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10110011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	iny

	RESTORE_AXY
	rts



BOXW_MIX_SHIFT3:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11001111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11001111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%11000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOXW_MIX_SHIFT4:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11111110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10110000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10000110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11111110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10000111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOXW_MIX_SHIFT5:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11111000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11000011
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%10011000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11111000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10011111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOXW_MIX_SHIFT6:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11100111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11100110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%10001100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11100110
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11100111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%11100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%11111111
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



