
; This file was generated by SpriteGenerator.py, a sprite generation tool by Quinn Dunki.
; If you feel the need to modify this file, you are probably doing it wrong.

BOX_GRN: ;4 bytes per row
	SAVE_AXY
	ldy PARAM0
	ldx MOD7_2,y
	jmp (BOX_GRN_JMP,x)

BOX_GRN_JMP:
	.addr BOX_GRN_SHIFT0
	.addr BOX_GRN_SHIFT1
	.addr BOX_GRN_SHIFT2
	.addr BOX_GRN_SHIFT3
	.addr BOX_GRN_SHIFT4
	.addr BOX_GRN_SHIFT5
	.addr BOX_GRN_SHIFT6


BOX_GRN_SHIFT0:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00101010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00101010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOX_GRN_SHIFT1:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00101000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000101
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00101000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000101
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOX_GRN_SHIFT2:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010101
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00010101
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOX_GRN_SHIFT3:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010101
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000001
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010101
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	iny

	RESTORE_AXY
	rts



BOX_GRN_SHIFT4:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00000100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010100
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00000010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	RESTORE_AXY
	rts



BOX_GRN_SHIFT5:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%00010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01010000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00001010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	RESTORE_AXY
	rts



BOX_GRN_SHIFT6:
	ldy PARAM0

	ldx PARAM1
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00101010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00100000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	inx
	lda HGRROWS_H,x
	sta SCRATCH1
	lda HGRROWS_L,x
	sta SCRATCH0
	ldy PARAM0
	lda DIV7_2,y
	tay

	iny
	lda #%01000000
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny
	lda #%00101010
	ora (SCRATCH0),y
	sta (SCRATCH0),y
	iny

	RESTORE_AXY
	rts



